### ISSUE TITLE
Does not start on Xubuntu 16.04 (and probably all Ubuntu flavors)

### ISSUE THREAD

**Issue by stacksmith** [Shinmera/portacle#16]
Cloned your repo into my home directory (`home/stack/`) 
- gui click on portacle.desktop as advised does nothing;
- executing `./portacle.run` in `/home/stack/portacle/` results in:
```
/home/stack/portacle//emacs/lin/emacs.sh: line 47: /home/stack/portacle//usr/lib/ld-linux.so: No such file or directory
```

P.S. I was away the last time I brought up this issue with 14.04 - sorry.  I am monitoring notifications and will be happy to assist you in debugging this if you are so inclined.

**Comment by Shinmera** [comment]
Cloning the repo is not the same as downloading a release.

If you clone the repo, you first need to build everything. See the instructions in `build/` for that.

**Comment by stacksmith** [comment]
Ah.  I did that first, but was not patient enough as it took about 15 seconds to show any life.  So I went to github to see if something got fixed.  It does works though.

There is a warning:
```
Warning: arch-dependent data dir '/home/linus/portacle/emacs/lin/libexec/emacs/25.1/x86_64-unknown-linux-gnu/': No such file or directory
```
But it does not seem to prevent it from running.

**Comment by Shinmera** [comment]
Right. The archive contains quite a lot of files, so it takes a good bit for your archive manager to show the contents.

And yes, that's a hardcoded path that gets compiled into emacs. Nothing I can do about that. All the paths to directories that emacs actually needs are adapted using environment variables in a wrapper script.

If you can't find anything else that doesn't run you're free to close this ticket.

**Comment by stacksmith** [comment]
Looks good - really good.  I like your emacs config, very clean.  I've been getting by keeping emacs, quicklisp and sbcl  in ~/Documents with lots of symlinks to a ~/Documents/config directory.  Your solution is much better.  Many thanks.

**Comment by Shinmera** [comment]
Glad to hear!
