### ISSUE TITLE
Gtk "atk-bridge" failed to load: libunity-gtk-module.so: undefined symbol: g_type_check_instance_is_fundamentally_a

### ISSUE THREAD

**Issue by maacl** [Shinmera/portacle#19]
On Ubuntu 16.10 I get:

```
➜  portacle git:(master) ✗ ./portacle.run 
Warning: arch-dependent data dir '/home/linus/portacle/emacs/lin/libexec/emacs/25.1/x86_64-unknown-linux-gnu/': No such file or directory
Gtk-Message: Failed to load module "atk-bridge"
/home/mac/Desktop/portacle/emacs/lin/bin/emacs: symbol lookup error: /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libunity-gtk-module.so: undefined symbol: g_type_check_instance_is_fundamentally_a
```

**Comment by Shinmera** [comment]
The "no such file or directory" thing can be ignored, it is of no consequence and something peculiar to the Emacs compilation that I cannot get rid of.

I'm not sure if your report means that Portacle does not launch at all, or just spews these warnings.

**Comment by maacl** [comment]
Sorry to be unclear. It does not launch at all. It exits with the last message above.

**Comment by Shinmera** [comment]
What happens if you try to run it like so:
```
GTK_MODULES="" GTK3_MODULES="" GTK2_MODULES="" ./portacle.run
```

**Comment by Shinmera** [comment]
Ok, got a VM now. Unsetting `GTK_MODULES` at least makes Emacs launch, but pretty much everything else breaks down.

**Comment by Shinmera** [comment]
I'll have to take a look at this some other time. Things are more bonkers than I thought possible.

**Comment by maacl** [comment]
Yeah, I can gte emacs to start with the above, but then I get:

```
(progn (load "/home/mac/Desktop/portacle/emacs/config/elpa/slime-20161109.640/swank-loader.lisp" :verbose t) (funcall (read-from-string "swank-loader:init")) (funcall (read-from-string "swank:start-server") "/tmp/slime.24084"))

/bin/bash: /home/mac/Desktop/portacle//usr/lin/lib/libtinfo.so.5: no version information available (required by /bin/bash)

Process inferior-lisp segmentation fault (core dumped)
```

**Comment by Shinmera** [comment]
It looks like system's bash completely freaks out when invoked under library environment that is shipped with portacle. Thus almost nothing works, because even an execve will invoke bash potentially.

I need to ship a portable bash, or an approximation thereof to fix this. That'll take some time to work out. Certainly won't get it done before Christmas, I got exams to worry about first.

**Comment by maacl** [comment]
BTW I am running ZSH as my shell - could that be a factor?

**Comment by Shinmera** [comment]
No, that makes no difference.

**Comment by Shinmera** [comment]
This has been fixed by the latest changes and should be officially available with the next release.
