### ISSUE TITLE
Please include the EVIL plugin, too

### ISSUE THREAD

**Issue by phmarek** [Shinmera/portacle#21]
So that people used to that other editor can more easily try that out, too.

Thanks a lot!

**Comment by Shinmera** [comment]
I don't think having evil activated by default would be a good idea for beginners. Otherwise, installing it is simple enough with emacs' package capabilities.

**Comment by phmarek** [comment]
Not activated, but available, with the explanation in the initially displayed file.

And no, it's not "simple" enough; I tried to follow the instructions a few times in the past, and never got it working.

**Comment by phmarek** [comment]
Thanks for the *very* quick answer, BTW!

**Comment by Shinmera** [comment]
That reminds me that the help file doesn't include an explanation of the package system yet and how to go about using that.

**Comment by Shinmera** [comment]
The help file includes a section on how to install and manage packages, including an example on how to do it through the user configuration file. That should clear this problem up.
