### ISSUE TITLE
SBCL logo missing on Portacle's website

### ISSUE THREAD

**Issue by TeMPOraL** [Shinmera/portacle#23]
https://shinmera.github.io/portacle/sbcl.svg -- this picture seems to be missing.

**Comment by Shinmera** [comment]
That's because SBCL does not really have a logo yet. See [SBCL's bug tracker](https://bugs.launchpad.net/sbcl/+bug/1644984).

**Comment by Shinmera** [comment]
I added a temporary logo until I get the time to bother people on SBCL to talk about a real logo again.
