### ISSUE TITLE
inferior-lisp segfault

### ISSUE THREAD

**Issue by S1ohy** [Shinmera/portacle#24]
Running GNU/Linux, Debian Sid 9.0. Executing portacle/portacle.run results in *inferior-lisp*  the following:

![2017-01-28 08 41 18](https://cloud.githubusercontent.com/assets/24659022/22401677/341fa8d2-e59a-11e6-8c54-923861f9281c.png)

Another interesting thing when you run portacle/portacle.run is the warning message 
> Warning: arch-dependent data dir '/home/linus/portacle/emacs/lin/libexec/emacs/25.1/x86_64-unknown-linux-gnu/': No such file or directory

**Comment by Shinmera** [comment]
Duplicate of #19
