### ISSUE TITLE
Magit Error "Nothing staged" on Win7

### ISSUE THREAD

**Issue by mfehlhaber** [Shinmera/portacle#26]
After staging some changes and trying to commit, I get the message `user-error: Nothing staged (or unstaged)`. Committing the same staged changes via command line using a locally installed git worked just fine.

Portacle 0.11 on Win7, updating all packages didn't help.

**Comment by Shinmera** [comment]
What does the Magit window look like before you try to commit? Are the changes that you staged listed under the "staged" section?

**Comment by mfehlhaber** [comment]
Yes, right up to commit things look & work just fine. I was able to commit my staged files via command line.

**Comment by Shinmera** [comment]
Ok, that's rather bizarre, then. I'll have to see if I can reproduce.

**Comment by Shinmera** [comment]
Confirmed the bug. Probably related to invalid behaviour for subprocesses in portacle-launcher.

**Comment by Shinmera** [comment]
The 0.11 release for Windows has been updated with the fix from Shinmera/portacle-launcher@236a2086255ab6a7fbfb5a4b5a7042cd4951565b included.
