### ISSUE TITLE
Include Hunspell for Win7

### ISSUE THREAD

**Issue by mfehlhaber** [Shinmera/portacle#27]
As spell checking is already part of portacle's configuration, I suggest to include Hunspell for Win users. Not having the means to build it myself, I fetched mine from https://sourceforge.net/projects/ezwinports/files/hunspell-1.3.2-3-w32-bin.zip which works fine.

**Comment by Shinmera** [comment]
I tried to get hunspell working before, but couldn't get it to work right. I might give it another shot in the future, but for now I don't want to bother with this.

**Comment by mfehlhaber** [comment]
Sorry, I surely am missing something here. All I did was download the binary package from the link above and extracting it into a directory `hunspell`. Making sure the path emacs uses includes `hunspell\bin`. Lastly setting `(setenv "DICTIONARY" "en_US")` to one of the dictionaries included. Now spellchecking works in portacle.

**Comment by Shinmera** [comment]
I don't like including solutions for a single platform only, and I don't like including pre-compiled binaries either. In order for things to be continuously buildable and as homogeneous as possible, I need to be able to ship it for all platforms, and I need to be able to build it from source.

**Comment by Shinmera** [comment]
Related commits: 
shinmera/portacle-launcher@8c80a8221aafd7b9cc44d3a0993631c0194f1bdb
shinmera/portacle-launcher@94f5587afb2eb9556e34bff8edb6f647a1e5d00f
shinmera/portacle-launcher@b24edd7a5226b1c1dc59efd3bb85845ed0f961df

**Comment by Shinmera** [comment]
Seems to be integrated and will be in release 0.12

**Comment by mfehlhaber** [comment]
Works great on Win7. Thank you very much.
