### ISSUE TITLE
Broken link to OSX download

### ISSUE THREAD

**Issue by svetlyak40wt** [Shinmera/portacle#28]
Page https://shinmera.github.io/portacle/ contains broken link to OSX release:

https://github.com/Shinmera/portacle/releases/download/0.11/mac-portacle.tar.xz

This link is in two places – header and text.

Correct link is:

https://github.com/Shinmera/portacle/releases/download/0.11/mac-portacle.dmg

**Comment by Shinmera** [comment]
Thanks-- I forgot to fix that when I switched over the format.

**Comment by svetlyak40wt** [comment]
By the way, great work! Will steal some configs into my emacs :)

**Comment by Shinmera** [comment]
You can find the bulk of the configuration source [here](https://github.com/Shinmera/.emacs)
