### ISSUE TITLE
GIT_ASKPASS not available on Win7

### ISSUE THREAD

**Issue by mfehlhaber** [Shinmera/portacle#29]
Just upgraded to the latest portacle (still 0.11) on my work box. Assuming your fix of `portacle-launcher` works since I did not get this far before...
```
git: 'credential-wincred' is not a git command. See 'git --help'.
error: cannot spawn git-gui--askpass: No such file or directory
bash.exe: warning: could not find /tmp, please create!
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Password for 'https://user@www.my-repo-site.com': No error
```
Wincred is not found, which in itself would be a minor inconvenience only. Unfortunately there does not seem to be a git-gui included, so that my setting of `(setenv "GIT_ASKPASS" "git-gui--askpass")` does not work here. Have you got any suggestion how I may be able to enter my git repository password?

**Comment by Shinmera** [comment]
I've looked into that this weekend, and haven't been able to find a good solution yet. The reason I excluded the git gui parts altogether is so to reduce the amount of dependencies I need to ship. I'll have to see if I can specifically include git-gui--askpass and none of the other bits, or if I do have to include git-gui altogether what I'd have to do to fix things up.

**Comment by Shinmera** [comment]
I might also look into a custom helper program that integrates well with Portacle, storing the credentials in a local file rather than using something attached to the system. That would make more sense for portability too.

I'll have to read the git credentials storage specs and see what I can do.

**Comment by Shinmera** [comment]
As per ce739e4 and Shinmera/portacle-launcher#b5aa1a4 this is now implemented.
