### ISSUE TITLE
(CFFI::FL-ERROR "Unable to load foreign library (~A).~%  ~A" GLIB::GLIB "Error opening shared object \"libglib-2.0-0.dll\": ..)

### ISSUE THREAD

**Issue by trayres** [Shinmera/portacle#33]
I tried the following:
`(ql:quickload "cl-cffi-gtk")`

Trying:
```
cffi:*foreign-library-directories*
Nil
```

I'm not sure if quicklisp or Portacle is having the problem; I believe you can get around it by setting up the FFI library path relative to Portacle root dir, but I haven't tried it yet (first time I've really tried CL is Portacle! It's amazing!)

**Comment by Shinmera** [comment]
I doubt that this has much of anything to do with Portacle. It looks much more like it's just an issue of CFFI not being able to find the needed library on your system. Are you sure that it's indeed installed?

**Comment by ukari** [comment]
you could set `cffi:*foreign-library-directories*` by yourself, like the following example
``` lisp
(pushnew #p"c:/Windows/System32/" cffi:*foreign-library-directories* :test #'equal)
(cffi:load-foreign-library "the-dll-you-miss.dll")
```

Here is the [link](https://common-lisp.net/project/cffi/manual/html_node/_002aforeign_002dlibrary_002ddirectories_002a.html#Examples-57)
