### ISSUE TITLE
Win10 default SLIME location does not respect installation path

### ISSUE THREAD

**Issue by MatthewRock** [Shinmera/portacle#34]
Today I tried using Portacle on friend's Windows PC. He didn't have any space on his main partition(?), so we installed it in other directory (P: drive). After installing, we successfully ran the Emacs; however, we encountered a problem during starting the SLIME - the path .slime could not be created. This was due to the lack of empty space, but SLIME tried to create its files on J:, when it was installed on P: and should - in my opinion - install everything there.

**Comment by Shinmera** [comment]
Ah, yeah. If I recall Slime uses its own heuristic to determine where to store its FASL cache. I'll have to see where I can customise that behaviour.

**Comment by MatthewRock** [comment]
Thanks for the quick response!

**Comment by Shinmera** [comment]
Alright, this seems to fix it. Please verify and close with the next release, once I get to putting that out.
