### ISSUE TITLE
ASLR Leads to Emacs Crash on Build

### ISSUE THREAD

**Issue by xsgb** [Shinmera/portacle#36]
Hi, I'm getting a segfault when building emacs from portacle. Didn't took time to investigate. On Debian unstable, gcc (Debian 6.3.0-13) 6.3.0 20170415

> make -C lib all
[...]
Loading /home/xs/brx/portacle/build/emacs/lisp/tooltip.el (source)...
Finding pointers to doc strings...
Finding pointers to doc strings...done
Dumping under the name emacs
Makefile:736: recipe for target 'bootstrap-emacs' failed
make[1]: *** [bootstrap-emacs] Segmentation fault
make[1]: Leaving directory '/home/xs/brx/portacle/build/emacs/src'
Makefile:398: recipe for target 'src' failed
make: *** [src] Error 2

**Comment by Shinmera** [comment]
What exactly did you do to arrive at that? Did you follow the instructions in the build readme exactly?

**Comment by xsgb** [comment]
Of course, from build/README.md, with all dependencies installed. 
Let me know if I can produce some gcc output by increasing the verbosity.

**Comment by xsgb** [comment]
Okay, it did exacly the same segfault after upgrading Debian, rebooting, "./build.sh clean" and "./build".

**Comment by Shinmera** [comment]
I'm not sure that this is a problem related to Portacle per se. It looks much more like a bug in Emacs itself. Unfortunately I'm not familiar with its inner workings, so I'm pretty much as much in the dark about this problem as you are.

**Comment by xsgb** [comment]
I'll take a look tomorrow if I can find the time! It will be the opportunity to test on my work machine (Debian 8). There's effectively something faulty between emacs and the installed libc, I'll check with another emacs tag too then.

**Comment by xsgb** [comment]
It's a bug related to emacs concerning a strange syscall named "personality" The workaround would be to disable « randomize_va_space » feature by doing:
>  echo 0 > /proc/sys/kernel/randomize_va_space

(even if it's not successful on each try..., It worked at least once for obscure reasons)
https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-05/msg00707.html

More explanations can be found there:
https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-05/msg00893.html

I'm closing the ticket since it's not related to portacle! Thanks for your work and sharing your passion. See you o/

xs

**Comment by Shinmera** [comment]
That's interesting. Can you see whether changing the kernel parameter circumvents #18 as well?
