### ISSUE TITLE
MacOS meta key is set to esc instead of option.

### ISSUE THREAD

**Issue by WhiskyRyan** [Shinmera/portacle#40]
MacOS meta key is set to esc instead of option.

**Comment by Shinmera** [comment]
Are you sure it isn't also Alt? I don't recall ever configuring Esc for any keybinding.

**Comment by WhiskyRyan** [comment]
I think it may be the way emacs is bundled into the portacle.app on macOS. I have no problems with standard emacs. On standard emacs I need to have "use option as meta key" checked in the terminal preferences... since the emacs in portacle.app does not run through the terminal I think maybe the meta (option) key is being shadowed by the macOS usage for typing special characters. For example M-x types "≈" in portacle.app emacs, but works just fine if I launch standard emacs from the terminal.

**Comment by Shinmera** [comment]
Should be fixed now.
