### ISSUE TITLE
portacle fails on Windows 10 Enterprise 2016 LTSB

### ISSUE THREAD

**Issue by osktyn** [Shinmera/portacle#42]
Download of latest build from official homesite fails during install step with:

"Portacle Installer: error

Non 7z archive."

The homepage mentions "After extraction", but the downloaded files is and exe and most recent 64-bit 7z fails to extract it anyway.

This happens both before and after I've installed 7-zip. This happens _after_ the prompt asking for installation base have been shown.

I can't test on other versions of Windows, so I have no input regarding how widespread the issue could be, but I have seen other mentions of USB installers/installs failing on Windows 10.  My current windows10 install is less than a week old.

**Comment by Shinmera** [comment]
You're supposed to just run the exe. It's a self-extracting archive, for the express purpose of not forcing people to install 7z first.

**Comment by Shinmera** [comment]
I haven't tested on 10 in a while, but I'd be surprised if things suddenly stopped working. Will have a look as soon as I have time.

**Comment by osktyn** [comment]
First I just executed the exe as I was supposed to and the problem occured as reported. This was before I had 7z installed.

**Comment by Shinmera** [comment]
I can't reproduce this on a completely freshly installed Windows 10 VM with all the updates installed. Have you made sure that the download of the file succeeded properly? Perhaps the file got corrupted.

**Comment by osktyn** [comment]
I did three separate file downloads and executions. Same result. I'll try to reproduce it on another machine one W10 enterprise tomorrow.

**Comment by Shinmera** [comment]
That's very, very strange. I can't really think of anything else that might play a role right now, unfortunately.

**Comment by osktyn** [comment]
It seems that you were on to it from the start:
* Two different W10 machines
* Four downloads from each
* Chrome signals the download as completed without errors
* Only 1/8 (!) have contained all the bytes to match the 86.6 mB files size
  * The first few downloads contained almost all the bytes so I missed the discrepancy.
  * The complete file executed fine and I am now a happy user of Portacle :)

I don't know if to close this as an unrelated network issue or keep it open in case it has to do with portacles source (amasonaws?). Your choice. Your complete code runs just fine.

**Comment by Shinmera** [comment]
Portacle is hosted on GitHub, so I don't really have much I can do about that. What I might offer though are checksums to verify that the download was completed correctly. I'll think about that.

I'm glad to hear you got it working after all, though!
