### ISSUE TITLE
Mac OS version

### ISSUE THREAD

**Issue by Keyframe** [Shinmera/portacle#44]
"You can’t use this version of the application ..." error when launching portacle. It says it needs 10.12. I've only noticed since I have El Capitan on my laptop and Sierra on desktop. Is this really necessary? If not, it could be solved by using a gcc flag -mmacosx-version-min=10.7 (10.7 is reasonable enough, no?).

**Comment by Shinmera** [comment]
It's not that easy, no. The problem is that the shared libraries the programs depend on start to diverge between OS X versions. I've built on 10.11 before, which still worked on 10.12, but building on 10.10 stopped things from working on 10.12.

**Comment by Shinmera** [comment]
Successfully did another build on 10.11 that still runs fine on 10.12. I'll try to continue supporting 10.11 for what it's worth.
