### ISSUE TITLE
Build Scripts Don't Exit on Error

### ISSUE THREAD

**Issue by gingeralesy** [Shinmera/portacle#7]
Emacs provided in lin64-portacle-0.0.3.tar.xz is linked against libgnutls.so.26, thus fails to launch on environments with libgnutls.so.28 instead. The user has to build emacs themselves on their local machine, making sure to install all the dependencies by hand.

Thankfully after installing them the build/emacs.sh works marvelously and Portacle will operate properly.

When attempting to build with build/all.sh without the dependencies installed however, the errors on failure to build emacs end up far up the process output and the user has to scroll up drastically to find the error messages.

**Comment by Shinmera** [comment]
See #4 for the SO problem. Since that part of this ticket is a dupe, I'll change this one to reflect the continue on error problem in the build scripts.
